### ISSUE TITLE
503's not being retried

### ISSUE THREAD

**Issue by eddie-scio** [googleapis/python-trace#56]
Across many of our GCP projects, we see trace export from GAE services failing with 503's consistently, but not always.

![Screen Shot 2020-10-27 at 11 59 31 AM](https://user-images.githubusercontent.com/52253266/97348798-e8a9fb80-184b-11eb-9869-45fd8a847fea.png)
![Screen Shot 2020-10-27 at 11 59 28 AM](https://user-images.githubusercontent.com/52253266/97348804-ea73bf00-184b-11eb-8dce-d937c4560c2b.png)
![Screen Shot 2020-10-27 at 11 59 23 AM](https://user-images.githubusercontent.com/52253266/97348807-eba4ec00-184b-11eb-876b-1b445cc1f74f.png)

The generated `trace_service_client_config.py` I'm seeing looks as follows:

```
config = {
    "interfaces": {
        "google.devtools.cloudtrace.v2.TraceService": {
            "retry_codes": {
                "idempotent": ["DEADLINE_EXCEEDED", "UNAVAILABLE"],
                "non_idempotent": [],
            },
            "retry_params": {
                "default": {
                    "initial_retry_delay_millis": 100,
                    "retry_delay_multiplier": 1.2,
                    "max_retry_delay_millis": 1000,
                    "initial_rpc_timeout_millis": 30000,
                    "rpc_timeout_multiplier": 1.5,
                    "max_rpc_timeout_millis": 60000,
                    "total_timeout_millis": 120000,
                }
            },
            "methods": {
                "BatchWriteSpans": {
                    "timeout_millis": 60000,
                    "retry_codes_name": "non_idempotent",
                    "retry_params_name": "default",
                },
                "CreateSpan": {
                    "timeout_millis": 60000,
                    "retry_codes_name": "idempotent",
                    "retry_params_name": "default",
                },
            },
        }
    }
}
```

And I'm wondering what we can do about this?  I understand that BatchWriteSpans is not an idempotent operation, so a 503 shouldn't necessarily be retried, but what can we do to understand why we're getting so many, and how to minimize the failures?

**Comment by busunkim96** [comment]
Hi @eddie-scio,

It looks like you're getting `Socket closed`.  Would you mind sharing what environment the code is being run in and a bit of the code?

One general recommendation is to save the client object and re-use it rather than creating many instances. This allows the auth token to be re-used until it expires.

Quick Reminder: If you have a support case with Google, please do open a case.

**Comment by eddie-scio** [comment]
Thanks for the quick reply and the reminder!

We are running this in Google App Engine Flex, with the following initialization:
```
from opencensus.common.transports.async_ import AsyncTransport

# If `entrypoint` is not defined in app.yaml, App Engine will look for an app
# called `app` in `main.py`.
app = Flask(__name__)

# See https://github.com/googleapis/google-api-python-client/issues/299.
logging.getLogger('googleapiclient.discovery_cache').setLevel(logging.ERROR)
_, project_id = auth.default()
if os.getenv('GAE_SERVICE'):  # Indicates this is running on GAE.
    Client().setup_logging(log_level=logging.INFO)
    logging.info('Exporting traces to Stackdriver...')
    trace_exporter = stackdriver_trace_exporter.StackdriverExporter(project_id=project_id, transport=AsyncTransport)
    middleware = FlaskMiddleware(
        app,
        exporter=trace_exporter,
        sampler=samplers.AlwaysOnSampler(),
        # TODO: Change to redlist / whatever FlaskMiddleware updates to.
        blacklist_paths=['liveness_check', 'readiness_check'])
else:
    logging.getLogger().setLevel(logging.INFO)

```

**Comment by eddie-scio** [comment]
I'm wondering if my usage of `tracer = execution_context.get_opencensus_tracer()` in the decorator is being affected by the fact that the above code I attached is top-level in my main App Engine binary, rather than within `if __name__ == '__main__':` as [per the docs](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/trace/cloud-trace-demo-app/app/app.py#L82).  I need to check their `RuntimeContext` implementation to understand if that small change makes a difference.

**Comment by eddie-scio** [comment]
> I'm wondering if my usage of `tracer = execution_context.get_opencensus_tracer()` in the decorator is being affected by the fact that the above code I attached is top-level in my main App Engine binary, rather than within `if __name__ == '__main__':` as [per the docs](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/trace/cloud-trace-demo-app/app/app.py#L82). I need to check their `RuntimeContext` implementation to understand if that small change makes a difference.

Oops, initialization under `__main__` is a no-op in Gunicorn on App Engine (local-only), so this is unrelated.

**Comment by busunkim96** [comment]
If this is actively causing pain, I would go ahead and pass a custom `retry` that includes 503 (or hand edit the ` trace_service_client_config.py`) . I'm not familiar with the integration with Open Census so I'm not sure which is easier.


@googleapis/api-logging Do any of you have ideas on what could be causing this?

**Comment by eddie-scio** [comment]
Creating a custom `google.cloud.trace.Client` that uses our own `retry` as suggested and will update with results.

**Comment by danoscarmike** [comment]
@eddie-scio I'm going to close this one out. Please feel free to comment or open a new issue if you're still having problems. Thanks!
