### ISSUE TITLE
Docs website is not updated for 1.1.0

### ISSUE THREAD

**Issue by eu42** [googleapis/python-trace#58]
If you check the [docs website](https://googleapis.dev/python/cloudtrace/latest/index.html), it still shows 1.0.0 as the latest release.

Also, `Migration Guide` link in changelog under v1.0.0 does not work in docs website, it is https://github.com/googleapis/python-trace/blob/master/UPGRADING, missing the extension somehow

**Comment by busunkim96** [comment]
@eu42 Thank you for the report! I've kicked off the docs job for 1.1.0. It should be published within the hour.
